services:
  _defaults:
    public: true

  prestashop.module.dpdshipping.form.type.dpdshipping_address:
    class: 'DpdShipping\Form\Configuration\Address\DpdShippingAddressType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  prestashop.module.dpdshipping.form.dpdshipping_address_form_data_provider:
    class: 'DpdShipping\Form\Configuration\Address\DpdShippingAddressFormDataProvider'
    arguments:
      - '@prestashop.core.query_bus'
      - '@prestashop.core.command_bus'

  prestashop.module.dpdshipping.form.dpdshipping_address_form_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.module.dpdshipping.form.dpdshipping_address_form_data_provider'
      - 'DpdShipping\Form\Configuration\Address\DpdShippingAddressType'
      - 'DpdShippingAddress'
  
  dpdshipping.grid.definition.factory.configuration.address:
    class: 'DpdShipping\Grid\Configuration\Address\Definition\Factory\AddressGridDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
    public: false
  
  dpdshipping.grid.query_builder.configuration.address:
    class: 'DpdShipping\Grid\Configuration\Address\Query\AddressQueryBuilder'
    parent: 'prestashop.core.grid.abstract_query_builder'
    public: true
    arguments:
      - '@prestashop.core.query.doctrine_search_criteria_applicator'
      - "@=service('prestashop.adapter.legacy.context').getContext().language.id"
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.id"
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.id_shop_group"
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.getGroup().share_stock"
      - '@prestashop.core.grid.query.filter.doctrine_filter_applicator'
  
  dpdshipping.grid.data_provider.configuration.address:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      - '@dpdshipping.grid.query_builder.configuration.address'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'dpdshipping_sender_address'
  
  dpdshipping.grid.factory.configuration.address:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    public: true
    arguments:
      - '@dpdshipping.grid.definition.factory.configuration.address'
      - '@dpdshipping.grid.data_provider.configuration.address'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'
