services:
  _defaults:
    public: true

  prestashop.module.dpdshipping.form.type.dpdshipping_carrier:
    class: 'DpdShipping\Form\Configuration\Carrier\DpdShippingCarrierType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  prestashop.module.dpdshipping.form.dpdshipping_carrier_form_data_provider:
    class: 'DpdShipping\Form\Configuration\Carrier\DpdShippingCarrierFormDataProvider'
    arguments:
      - '@prestashop.core.query_bus'
      - '@prestashop.core.command_bus'
      - '@prestashop.module.dpdshipping.domain.carrier.handler'
      - '@translator'

  prestashop.module.dpdshipping.form.dpdshipping_carrier_form_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.module.dpdshipping.form.dpdshipping_carrier_form_data_provider'
      - 'DpdShipping\Form\Configuration\Carrier\DpdShippingCarrierType'
      - 'DpdShippingCarrier'
