services:
  _defaults:
    public: true

  prestashop.module.dpdshipping.form.type.dpdshipping_onboarding:
    class: 'DpdShipping\Form\Configuration\Onboarding\DpdShippingOnboardingType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  prestashop.module.dpdshipping.form.dpdshipping_onboarding_form_data_provider:
    class: 'DpdShipping\Form\Configuration\Onboarding\DpdShippingOnboardingFormDataProvider'
    arguments:
      - '@prestashop.core.query_bus'
      - '@prestashop.core.command_bus'
      - '@prestashop.module.dpdshipping.domain.carrier.handler'

  prestashop.module.dpdshipping.form.dpdshipping_onboarding_form_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.module.dpdshipping.form.dpdshipping_onboarding_form_data_provider'
      - 'DpdShipping\Form\Configuration\Onboarding\DpdShippingOnboardingType'
      - 'DpdShippingOnboarding'

  prestashop.module.dpdshipping.domain.onboarding.query_handler.get_configuration:
    class: 'DpdShipping\Domain\Configuration\Onboarding\Query\GetOnboardingHandler'
    arguments:
      - '@prestashop.adapter.legacy.configuration'
    tags:
      - name: tactician.handler
        command: 'DpdShipping\Domain\Configuration\Onboarding\Query\GetOnboarding'

  prestashop.module.dpdshipping.domain.onboarding.command_handler.save_configuration:
    class: 'DpdShipping\Domain\Configuration\Onboarding\Command\SaveOnboardingHandler'
    arguments:
      - '@prestashop.adapter.legacy.configuration'
    tags:
      - name: tactician.handler
        command: 'DpdShipping\Domain\Configuration\Onboarding\Command\SaveOnboardingCommand'
