services:
  _defaults:
    public: true

  prestashop.module.dpdshipping.form.type.dpdshipping_special_prices:
    class: 'DpdShipping\Form\Configuration\SpecialPrice\DpdShippingSpecialPriceType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  prestashop.module.dpdshipping.form.dpdshipping_special_prices_form_data_provider:
    class: 'DpdShipping\Form\Configuration\SpecialPrice\DpdShippingSpecialPriceFormDataProvider'
    arguments:
      - '@prestashop.core.query_bus'
      - '@prestashop.core.command_bus'

  prestashop.module.dpdshipping.form.dpdshipping_special_prices_form_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.module.dpdshipping.form.dpdshipping_special_prices_form_data_provider'
      - 'DpdShipping\Form\Configuration\SpecialPrice\DpdShippingSpecialPriceType'
      - 'DpdShippingSpecialPrice'
