services:
  _defaults:
    public: true

  prestashop.module.dpdshipping.form.type.dpdshipping_pickup_courier_edit:
    class: 'DpdShipping\Form\PickupCourier\DpdShippingPickupCourierEditType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }
    arguments:
      [ '@prestashop.module.dpdshipping.form.dpdshipping_pickup_courier_edit_form_data_provider' ]

  prestashop.module.dpdshipping.form.dpdshipping_pickup_courier_edit_form_data_provider:
    class: 'DpdShipping\Form\PickupCourier\DpdShippingPickupCourierEditFormDataProvider'
    arguments: [ '@prestashop.core.query_bus', '@prestashop.core.command_bus' ]

  prestashop.module.dpdshipping.form.dpdshipping_pickup_courier_edit_form_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.module.dpdshipping.form.dpdshipping_pickup_courier_edit_form_data_provider'
      - 'DpdShipping\Form\PickupCourier\DpdShippingPickupCourierEditType'
      - 'DpdShippingPickupCourierEdit'
