services:
  _defaults:
    public: true

  prestashop.module.dpdshipping.domain.payer.query.get.payer.list.handler:
    class: 'DpdShipping\Domain\Configuration\Payer\Query\GetPayerListHandler'
    arguments:
      - '@prestashop.module.dpdshipping.repository.dpdshipping.payer.repository'
    tags:
      - name: tactician.handler
        command: 'DpdShipping\Domain\Configuration\Payer\Query\GetPayerList'

  prestashop.module.dpdshipping.domain.payer.query.get.default.payer.handler:
    class: 'DpdShipping\Domain\Configuration\Payer\Query\GetDefaultPayerHandler'
    arguments:
      - '@prestashop.module.dpdshipping.repository.dpdshipping.payer.repository'
    tags:
      - name: tactician.handler
        command: 'DpdShipping\Domain\Configuration\Payer\Query\GetDefaultPayer'

  prestashop.module.dpdshipping.domain.payer.command.add.payer.handler:
    class: 'DpdShipping\Domain\Configuration\Payer\Command\AddPayerHandler'
    arguments:
      - '@prestashop.module.dpdshipping.repository.dpdshipping.payer.repository'
    tags:
      - name: tactician.handler
        command: 'DpdShipping\Domain\Configuration\Payer\Command\AddPayerCommand'
